version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
